[package]
name = "nuka-nu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embed-nu = "0.8"
object = "0.30"
